//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TricksterMap {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TricksterMap.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collision Data.
        /// </summary>
        internal static string CollisionData {
            get {
                return ResourceManager.GetString("CollisionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Layer - Collision Data ({0}).
        /// </summary>
        internal static string CollisionFormTitle {
            get {
                return ResourceManager.GetString("CollisionFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Point Object.
        /// </summary>
        internal static string CreatePointObject {
            get {
                return ResourceManager.GetString("CreatePointObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Range Object.
        /// </summary>
        internal static string CreateRangeObject {
            get {
                return ResourceManager.GetString("CreateRangeObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Point Object.
        /// </summary>
        internal static string EditPointObject {
            get {
                return ResourceManager.GetString("EditPointObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Range Object.
        /// </summary>
        internal static string EditRangeObject {
            get {
                return ResourceManager.GetString("EditRangeObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string FileExit {
            get {
                return ResourceManager.GetString("FileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string FileOpen {
            get {
                return ResourceManager.GetString("FileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General NPC.
        /// </summary>
        internal static string GeneralNPC {
            get {
                return ResourceManager.GetString("GeneralNPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ground Type.
        /// </summary>
        internal static string GroundType {
            get {
                return ResourceManager.GetString("GroundType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GvG Spawn Range.
        /// </summary>
        internal static string GvGSpawnRange {
            get {
                return ResourceManager.GetString("GvGSpawnRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height Data.
        /// </summary>
        internal static string HeightData {
            get {
                return ResourceManager.GetString("HeightData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Trickster map file..
        /// </summary>
        internal static string InvalidMapFileError {
            get {
                return ResourceManager.GetString("InvalidMapFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Control ({0}).
        /// </summary>
        internal static string MapControl {
            get {
                return ResourceManager.GetString("MapControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map ID.
        /// </summary>
        internal static string MapID {
            get {
                return ResourceManager.GetString("MapID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster Gather Range.
        /// </summary>
        internal static string MonsterGatherRange {
            get {
                return ResourceManager.GetString("MonsterGatherRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster Movement Range.
        /// </summary>
        internal static string MonsterMovementRange {
            get {
                return ResourceManager.GetString("MonsterMovementRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster Spawn.
        /// </summary>
        internal static string MonsterSpawnPoint {
            get {
                return ResourceManager.GetString("MonsterSpawnPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster Spawn Range.
        /// </summary>
        internal static string MonsterSpawnRange {
            get {
                return ResourceManager.GetString("MonsterSpawnRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NORI Entity.
        /// </summary>
        internal static string NORIEntity {
            get {
                return ResourceManager.GetString("NORIEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Walkable.
        /// </summary>
        internal static string NotWalkable {
            get {
                return ResourceManager.GetString("NotWalkable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPC Movement Range.
        /// </summary>
        internal static string NPCMovementRange {
            get {
                return ResourceManager.GetString("NPCMovementRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}.
        /// </summary>
        internal static string NumOfNum {
            get {
                return ResourceManager.GetString("NumOfNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trickster Map Data Files (*.md3).
        /// </summary>
        internal static string OpenType {
            get {
                return ResourceManager.GetString("OpenType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Object Data ({0}).
        /// </summary>
        internal static string PointObjectView {
            get {
                return ResourceManager.GetString("PointObjectView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal.
        /// </summary>
        internal static string Portal {
            get {
                return ResourceManager.GetString("Portal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal Entrance Range.
        /// </summary>
        internal static string PortalEntranceRange {
            get {
                return ResourceManager.GetString("PortalEntranceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segoe UI.
        /// </summary>
        internal static string PreferredFont {
            get {
                return ResourceManager.GetString("PreferredFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range Object View.
        /// </summary>
        internal static string RangeObjectView {
            get {
                return ResourceManager.GetString("RangeObjectView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respawn Location.
        /// </summary>
        internal static string RespawnLocation {
            get {
                return ResourceManager.GetString("RespawnLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        internal static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Debris (?).
        /// </summary>
        internal static string SetDebris {
            get {
                return ResourceManager.GetString("SetDebris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop NPC.
        /// </summary>
        internal static string ShopNPC {
            get {
                return ResourceManager.GetString("ShopNPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Shop NPC.
        /// </summary>
        internal static string SkillNPC {
            get {
                return ResourceManager.GetString("SkillNPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Effects.
        /// </summary>
        internal static string SpecialEffects {
            get {
                return ResourceManager.GetString("SpecialEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleport Item Spawn.
        /// </summary>
        internal static string TeleportItemSpawn {
            get {
                return ResourceManager.GetString("TeleportItemSpawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleport NPC Spawn.
        /// </summary>
        internal static string TeleportNPCSpawn {
            get {
                return ResourceManager.GetString("TeleportNPCSpawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile View ({0}).
        /// </summary>
        internal static string TileView {
            get {
                return ResourceManager.GetString("TileView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown ({0}).
        /// </summary>
        internal static string UnknownType {
            get {
                return ResourceManager.GetString("UnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walkable.
        /// </summary>
        internal static string Walkable {
            get {
                return ResourceManager.GetString("Walkable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X1.
        /// </summary>
        internal static string X1Pos {
            get {
                return ResourceManager.GetString("X1Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X2.
        /// </summary>
        internal static string X2Pos {
            get {
                return ResourceManager.GetString("X2Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string XPos {
            get {
                return ResourceManager.GetString("XPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X: {0}.
        /// </summary>
        internal static string XSize {
            get {
                return ResourceManager.GetString("XSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y1.
        /// </summary>
        internal static string Y1Pos {
            get {
                return ResourceManager.GetString("Y1Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y2.
        /// </summary>
        internal static string Y2Pos {
            get {
                return ResourceManager.GetString("Y2Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string YPos {
            get {
                return ResourceManager.GetString("YPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y: {0}.
        /// </summary>
        internal static string YSize {
            get {
                return ResourceManager.GetString("YSize", resourceCulture);
            }
        }
    }
}
