//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace md3_2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("md3_2.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string FileExit {
            get {
                return ResourceManager.GetString("FileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string FileOpen {
            get {
                return ResourceManager.GetString("FileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General NPC.
        /// </summary>
        internal static string GeneralNPC {
            get {
                return ResourceManager.GetString("GeneralNPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map ID.
        /// </summary>
        internal static string MapID {
            get {
                return ResourceManager.GetString("MapID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster Spawn.
        /// </summary>
        internal static string MonsterSpawnPoint {
            get {
                return ResourceManager.GetString("MonsterSpawnPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respawn Location.
        /// </summary>
        internal static string RespawnLocation {
            get {
                return ResourceManager.GetString("RespawnLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop NPC.
        /// </summary>
        internal static string ShopNPC {
            get {
                return ResourceManager.GetString("ShopNPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleport Item Spawn.
        /// </summary>
        internal static string TeleportItemSpawn {
            get {
                return ResourceManager.GetString("TeleportItemSpawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleport NPC Spawn.
        /// </summary>
        internal static string TeleportNPCSpawn {
            get {
                return ResourceManager.GetString("TeleportNPCSpawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string XPos {
            get {
                return ResourceManager.GetString("XPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string YPos {
            get {
                return ResourceManager.GetString("YPos", resourceCulture);
            }
        }
    }
}
